services:
  app:
    image: file-search-service:0.1
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    ports:
      - 28080:8080
    restart: always
    networks:
      - common-network
    environment:
      - MINIO_SERVER_ACCESS_KEY=minio
      - MINIO_SERVER_SECRET_KEY=miniosecret
      - MINIO_SERVER_URL=http://minio:9000
      - SPRING_DATA_MONGODB_URI=mongodb://admin:Admin1234@mongo:27017/test?authSource=admin
networks:
  common-network:
    external: true