spring:
    datasource:
        url: jdbc:postgresql://psql/aistudio-data
        username: postgres
        password: Admin1234
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate.format_sql: true
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

    kafka:
        bootstrap-servers: kafka:9092
        producer:
            acks: 1
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            properties:
                "producer.idempotence": "false"
        listener:
            missing-topics-fatal: false

    data:
        mongodb:
            uri: mongodb://admin:Admin1234@mongo:27017/test?authSource=admin
        elasticsearch:
            rest:
                uris: "http://elasticsearch:9200"
            repositories:
                enabled: true
        redis:
            host: redis
            port: 6379
            password: Admin1234
            timeout: 30000 #30초

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

    jwt:
        secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalasfdbfbnfnaabers

server:
    port: 8080

springdoc:
  swagger-ui:
    path: /api/swagger-ui
  api-docs:
    path: /api/api-docs
    enabled: true

minio:
    url: http://minio:9000
    access-key: minio
    secret-key: miniosecret
    bucket-name: aistudio-data

